package sbnz.integracija;

import sbnz.integracija.example.model.MernaStanica;
import sbnz.integracija.example.model.GlavnaStanica;

rule "Padavine podizu vodostaj"
    no-loop
    when
        $s: MernaStanica( padavine >= 0 )
    then
        $s.kisa();
        update($s);
end

rule "Provera padavina"
    when
        $s: MernaStanica( padavine >= 30 , nivoVode >= maxNivo*0.8 )
    then
        $s.setAlarm(true);
     //   $s.gStanica.proveraAlarma();
        update($s);
end


rule "Nivo vode"
    no-loop
    when
        $i: MernaStanica( nivoVode >= maxNivo)
    then
        $i.setAlarm(true);
        update($i);
end