package sbnz.integracija;

import sbnz.integracija.example.model.GlavnaStanica;


rule "Nivo jezera previsok"
    when
        $i: GlavnaStanica( nivoVode >= maxVode, otvorena == false )
    then
        $i.setOtvorena(true);
        update($i);
end

rule "Nivo jezera prenizak"
    when
        $i: GlavnaStanica( nivoVode <= minVode, otvorena == true )
    then
        $i.setOtvorena(false);
        update($i);
end

rule "Ispustanje vode"
    when
        $i: GlavnaStanica(otvorena == true, nivoVode >= (nivoVode + minVode)/2 )
        
    then
   
        $i.ispustiVodu();
        System.out.println("Trenutni nivo:" + $i.getNivoVode());
        update($i);
end

rule "Provera stanica"
	lock-on-active
	when
        $i: GlavnaStanica(otvorena == false, proveraAlarma() == true )
    then
        $i.setOtvorena(true);
        update($i);
end
